### ISSUE TITLE
Errors while deploying in vercel

### ISSUE THREAD

**Issue by Adarshagupta** [HumeAI/hume-evi-next-js-starter#3]
at t0 (/vercel/path0/.next/server/app/page.js:14:214522)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: '3731050089'
}
Error
    at t0 (/vercel/path0/.next/server/app/page.js:14:214522)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: '3731050089'
}
Error
    at t0 (/vercel/path0/.next/server/app/page.js:14:214522)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: '3731050089'
}
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
Error
    at t0 (/vercel/path0/.next/server/app/page.js:14:214522)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 ✓ Generating static pages (5/5)

**Comment by jaid-monwr** [comment]
Hi @Adarshagupta , I was facing the same issue when running on my local machine. I did not try deploying it yet however I had similar errors with accessToken. This is how I FIXED my issue:

Solution:
1. Open the file getHumeAccessToken.ts under utils folder
2. Rename the variable clientSecret to secretKey in:

```
const accessToken = await fetchAccessToken({
    apiKey: String(process.env.HUME_API_KEY),
    secretKey: String(process.env.HUME_CLIENT_SECRET),
  });
```
  
 That should fix your problem.

**Comment by zachkrall** [comment]
Hi @Adarshagupta, thanks for reaching out. I think this is all ironed out as of the latest version. Feel free to reach out if you run into any other issues.
